### ISSUE TITLE
Not sure what to replace SMS_RECIPIENT with

### ISSUE THREAD

**Issue by CrimsonTide0** [drahnr/messagebird-async#7]
Hi, I think I'm misunderstanding the proper format to replace SMS_RECIPIENT with. The code compiles without any errors or warnings but when I run it the thread panics at the first expect.

This is the code where it panics, I've substituted the last four numbers with Xs for privacy reasons but in reality, they're numbers. 1 is the country code as I live in the United States; I've tried it without the 1 as well.
```
let msisdn_str = std::env::var("1201957XXXX".to_string())
        .expect("SMS_RECIPIENT should contain the number without prefix");
```

Also on a side note, do you plan on updating your futures in dependencies as well as the code for examples/send.rs because recent versions of futures don't have the and_then method that is used in 'let fut = ' in examples/send.rs

**Comment by drahnr** [comment]
```
let msisdn_str = std::env::var("1201957XXXX".to_string())
        .expect("SMS_RECIPIENT should contain the number without prefix");
```
tries to load the env variable **named** `1201957XXXX`, which is not what you want.

Either use 

```rust
let msisdn_str = "1201957XXXX";
```

directly, 

**OR**

 leave the code as is in latest master and make sure the `SMS_RECIPIENT` is exported by validating with `env` shell command.

---

Let me know how it goes, or make a PR so I can give more precise suggestions :)

**Comment by CrimsonTide0** [comment]
Hi drahnr, thanks for your help. I'm getting a new error now when I run the program saying Error: Access Key Error {msg: "env"}
Is it because I never ran the first two lines of code illustrated in the crate? 
export MESSAGEBIRD_ACCESSKEY=abio8usad..dfahdk
export SMS_RECIPIENT=1234556
Is it possible replace the code so that I don't have to run the export commands?

**Comment by CrimsonTide0** [comment]
This is my current code as is:
```
#[macro_use]
extern crate log;
extern crate env_logger;
extern crate futures;
extern crate messagebird_async;
extern crate tokio_core;

use futures::future::Future;
use messagebird_async::errors::*;
use messagebird_async::sms;
use messagebird_async::sms::*;

fn main() -> Result<(), MessageBirdError> {
    env_logger::init();

    let msisdn_str = "12019575008";
    let msisdn: Msisdn = Msisdn::from_str(msisdn_str)
        .expect("SMS_RECIPIENT did not contain a valid number");

    info!("example: sending a message");
    let sendable = sms::send::SendParameters::builder()
        .payload(
            PayloadType::Sms,
            Payload::Text("fun".to_string()),
            PayloadEncoding::Auto,
        )
        .origin(AlphaNumeric("inbox".to_string()).into())
        .add_recipient(msisdn.into())
        .build();

    let accesskey = AccessKey::from_env()?;
    let fut = RequestSend::new(&sendable, &accesskey);
    let fut = fut.and_then(|sent_msg: Message| {
        info!("{:?}", sent_msg);
        futures::future::ok(())
    });
    let mut core = tokio_core::reactor::Core::new().unwrap();
    core.run(fut.map(|_| ()))
}
```

**Comment by drahnr** [comment]
You need to replace `AccessKey::from_env()?;` with `AccessKey::from_str(sdfi0fj..989f")?`

I'd recommend you to checkout the documentation under https://docs.rs/messagebird-async/0.5.0/src/messagebird_async/sms/async/send.rs.html

**Comment by CrimsonTide0** [comment]
Hi is AccessKey::from_str("sdfi0fj..989f")? an example of a real access key? If so, how can I get access to a real one? If not, I tried replacing AccessKey::from_env()?; with AccessKey::from_str("sdfi0fj..989f")? but it says that it's an incorrect access key. Do you need to get an access key through the actual messagebird site?

**Comment by drahnr** [comment]
You need to go to the messagebird website, register, and load your account with some credits.

**Comment by CrimsonTide0** [comment]
I see and then it charges me for each sms message I send, is that correct? Is there a plan where you get charged a flat rate per month and then am allowed to send as many sms messages as desired?

**Comment by drahnr** [comment]
I think it depends on volume, but since I am no affiliated with messagebird in any way, I can't really tell. The website is the sole authority here :)

---

A request for future issues :star2: 

I would like to ask you, to copy the error messages you see verbatim (with redacted credentials where necessary) into the issues here. That makes triaging a lot easier for me. It would also help if you'd state your level of rust experience to know what kind of support would help you the most. :beginner: / :man_teacher: 

Closing this, since I think all you need is an access key :smile: 

Feel free to re-open this or open a new issues if you encounter new issues! :warning:

**Comment by CrimsonTide0** [comment]
Ok thank you for all your help.
